import { QuestionPaper, Video, Feedback, User } from "@shared/schema";

// Mock question papers data
export const mockQuestionPapers: QuestionPaper[] = [
  {
    id: "1",
    title: "Mathematics Phase 1 - 2024",
    class: 10,
    subject: "Mathematics",
    year: 2024,
    phase: "Phase 1",
    fileUrl: "/papers/math-10-2024-p1.pdf",
    createdAt: new Date("2024-03-15"),
  },
  {
    id: "2",
    title: "Science Phase 2 - 2024",
    class: 10,
    subject: "Science",
    year: 2024,
    phase: "Phase 2",
    fileUrl: "/papers/science-10-2024-p2.pdf",
    createdAt: new Date("2024-06-20"),
  },
  {
    id: "3",
    title: "Physics Board Exam - 2023",
    class: 12,
    subject: "Physics",
    year: 2023,
    phase: "Board Exam",
    fileUrl: "https://drive.google.com/file/d/1xyzPhysics12NBSE2023/view",
    createdAt: new Date("2023-02-28"),
  },
  {
    id: "4",
    title: "Chemistry Board Exam - 2023",
    class: 12,
    subject: "Chemistry",
    year: 2023,
    phase: "Board Exam",
    fileUrl: "https://drive.google.com/file/d/1abcChemistry12NBSE2023/view",
    createdAt: new Date("2023-03-15"),
  },
  {
    id: "5",
    title: "Biology Board Exam - 2024",
    class: 12,
    subject: "Biology",
    year: 2024,
    phase: "Board Exam",
    fileUrl: "https://drive.google.com/file/d/1defBiology12NBSE2024/view",
    createdAt: new Date("2024-03-20"),
  },
  {
    id: "6",
    title: "Mathematics Board Exam - 2024",
    class: 12,
    subject: "Mathematics",
    year: 2024,
    phase: "Board Exam",
    fileUrl: "https://drive.google.com/file/d/1ghiMath12NBSE2024/view",
    createdAt: new Date("2024-03-25"),
  },
  {
    id: "7",
    title: "Physics Board Exam - 2024",
    class: 11,
    subject: "Physics",
    year: 2024,
    phase: "Board Exam",
    fileUrl: "https://drive.google.com/file/d/1jklPhysics11NBSE2024/view",
    createdAt: new Date("2024-03-10"),
  },
  {
    id: "8",
    title: "Chemistry Board Exam - 2024",
    class: 11,
    subject: "Chemistry",
    year: 2024,
    phase: "Board Exam",
    fileUrl: "https://drive.google.com/file/d/1mnoChemistry11NBSE2024/view",
    createdAt: new Date("2024-03-12"),
  },
  {
    id: "9",
    title: "Biology Board Exam - 2024",
    class: 11,
    subject: "Biology",
    year: 2024,
    phase: "Board Exam",
    fileUrl: "https://drive.google.com/file/d/1pqrBiology11NBSE2024/view",
    createdAt: new Date("2024-03-18"),
  },
  {
    id: "10",
    title: "Mathematics Board Exam - 2023",
    class: 11,
    subject: "Mathematics",
    year: 2023,
    phase: "Board Exam",
    fileUrl: "https://drive.google.com/file/d/1stuMath11NBSE2023/view",
    createdAt: new Date("2023-03-22"),
  },
  {
    id: "11",
    title: "Social Science Phase 1 - 2024",
    class: 9,
    subject: "Social Science",
    year: 2024,
    phase: "Phase 1",
    fileUrl: "/papers/social-9-2024-p1.pdf",
    createdAt: new Date("2024-03-10"),
  },
];

// Mock videos data
export const mockVideos: Video[] = [
  {
    id: "1",
    title: "Physics - Newton's Laws of Motion (Class 11)",
    description: "Complete explanation of Newton's three laws of motion with real-world examples and problem solving for NBSE Class 11 Physics",
    class: 11,
    subject: "Physics",
    youtubeUrl: "https://www.youtube.com/watch?v=kKKM8Y-u7ds",
    thumbnailUrl: "https://img.youtube.com/vi/kKKM8Y-u7ds/maxresdefault.jpg",
    createdAt: new Date("2024-01-15"),
    duration: "15:30",
    views: 1250,
    uploadDate: "2024-01-15",
    category: "Physics",
  },
  {
    id: "2",
    title: "Chemistry - Atomic Structure (Class 11)",
    description: "Detailed study of atomic structure, electron configuration, and quantum numbers for NBSE Class 11 Chemistry",
    class: 11,
    subject: "Chemistry",
    youtubeUrl: "https://www.youtube.com/watch?v=W2Xb2GFK2yc",
    thumbnailUrl: "https://img.youtube.com/vi/W2Xb2GFK2yc/maxresdefault.jpg",
    createdAt: new Date("2024-01-20"),
    duration: "18:45",
    views: 980,
    uploadDate: "2024-01-20",
    category: "Chemistry",
  },
  {
    id: "3",
    title: "Biology - Cell Division: Mitosis and Meiosis (Class 12)",
    description: "Complete explanation of cell division processes including mitosis and meiosis for NBSE Class 12 Biology",
    class: 12,
    subject: "Biology",
    youtubeUrl: "https://www.youtube.com/watch?v=VzPD009qTN4",
    thumbnailUrl: "https://img.youtube.com/vi/VzPD009qTN4/maxresdefault.jpg",
    createdAt: new Date("2024-01-25"),
    duration: "22:15",
    views: 1450,
    uploadDate: "2024-01-25",
    category: "Biology",
  },
  {
    id: "4",
    title: "Mathematics - Calculus: Derivatives (Class 12)",
    description: "Introduction to derivatives, rules of differentiation, and applications for NBSE Class 12 Mathematics",
    class: 12,
    subject: "Mathematics",
    youtubeUrl: "https://www.youtube.com/watch?v=WUvTyaaNkzM",
    thumbnailUrl: "https://img.youtube.com/vi/WUvTyaaNkzM/maxresdefault.jpg",
    createdAt: new Date("2024-02-05"),
    duration: "25:40",
    views: 1820,
    uploadDate: "2024-02-05",
    category: "Mathematics",
  },
  {
    id: "5",
    title: "Physics - Electromagnetic Induction (Class 12)",
    description: "Understanding Faraday's law, Lenz's law, and electromagnetic induction for NBSE Class 12 Physics",
    class: 12,
    subject: "Physics",
    youtubeUrl: "https://www.youtube.com/watch?v=fHztCSCQrQI",
    thumbnailUrl: "https://img.youtube.com/vi/fHztCSCQrQI/maxresdefault.jpg",
    createdAt: new Date("2024-02-15"),
    duration: "20:10",
    views: 1350,
    uploadDate: "2024-02-15",
    category: "Physics",
  },
  {
    id: "6",
    title: "Chemistry - Organic Chemistry Basics (Class 11)",
    description: "Introduction to organic chemistry, IUPAC nomenclature, and functional groups for NBSE Class 11",
    class: 11,
    subject: "Chemistry",
    youtubeUrl: "https://www.youtube.com/watch?v=hOCEAMPo6iM",
    thumbnailUrl: "https://img.youtube.com/vi/hOCEAMPo6iM/maxresdefault.jpg",
    createdAt: new Date("2024-01-25"),
    duration: "19:25",
    views: 1120,
    uploadDate: "2024-01-25",
    category: "Chemistry",
  },
  {
    id: "7",
    title: "Biology - Photosynthesis Process (Class 11)",
    description: "Detailed explanation of photosynthesis, light and dark reactions for NBSE Class 11 Biology",
    class: 11,
    subject: "Biology",
    youtubeUrl: "https://www.youtube.com/watch?v=uixA8ZXx0KU",
    thumbnailUrl: "https://img.youtube.com/vi/uixA8ZXx0KU/maxresdefault.jpg",
    createdAt: new Date("2024-02-20"),
    duration: "17:50",
    views: 950,
    uploadDate: "2024-02-20",
    category: "Biology",
  },
  {
    id: "8",
    title: "Mathematics - Trigonometry Advanced (Class 11)",
    description: "Advanced trigonometry concepts, identities, and equations for NBSE Class 11 Mathematics",
    class: 11,
    subject: "Mathematics",
    youtubeUrl: "https://www.youtube.com/watch?v=yBw67Fb31Cs",
    thumbnailUrl: "https://img.youtube.com/vi/yBw67Fb31Cs/maxresdefault.jpg",
    createdAt: new Date("2024-01-30"),
    duration: "23:15",
    views: 1580,
    uploadDate: "2024-01-30",
    category: "Mathematics",
  },
];

// Mock feedback data
export const mockFeedback: Feedback[] = [
  {
    id: "1",
    name: "Priya Sharma",
    email: "priya.sharma@email.com",
    message: "This platform has been incredibly helpful for my NBSE preparation. The question papers are well organized and the video explanations are clear and easy to understand.",
    rating: 5,
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "2",
    name: "Rohan Kumar",
    email: "rohan.k@email.com",
    message: "Great resource for NBSE students! I especially love the filtering options that help me find exactly what I need for my class and subject.",
    rating: 4,
    createdAt: new Date("2024-01-12"),
  },
  {
    id: "3",
    name: "Anita Das",
    email: null,
    message: "The free access to all materials is amazing. As a student from a rural area, this platform has given me the same resources as students in the city.",
    rating: 5,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "4",
    name: "Vikash Singh",
    email: "vikash.singh@email.com",
    message: "The mobile-friendly design is perfect. I can study on my phone during my commute to school. Thank you for making education accessible!",
    rating: 5,
    createdAt: new Date("2024-01-18"),
  },
  {
    id: "5",
    name: "Meera Patel",
    email: null,
    message: "The concept videos have helped me understand topics that I was struggling with in class. The explanations are much clearer than my textbooks.",
    rating: 4,
    createdAt: new Date("2024-01-20"),
  },
];

// Mock users data
export const mockUsers: User[] = [
  {
    id: "user-1",
    username: "student1",
    password: "password123",
    mobile: "+919876543210",
    role: "user",
  },
  {
    id: "user-2",
    username: "student2",
    password: "password123",
    mobile: "+919876543211",
    role: "user",
  },
];

// Statistics data
export const mockStats = {
  totalPapers: mockQuestionPapers.length,
  totalVideos: mockVideos.length,
  totalUsers: mockUsers.length,
  totalFeedback: mockFeedback.length,
};

// Subject categories for videos
export const subjectCategories = [
  {
    name: "Mathematics",
    icon: "📐",
    color: "bg-pink-50 border-pink-200",
    description: "Algebra, Geometry, Trigonometry and more",
  },
  {
    name: "Science",
    icon: "🧪",
    color: "bg-blue-50 border-blue-200",
    description: "Physics, Chemistry, Biology concepts",
  },
  {
    name: "English",
    icon: "📚",
    color: "bg-green-50 border-green-200",
    description: "Grammar, Literature, Writing skills",
  },
  {
    name: "Social Science",
    icon: "🌍",
    color: "bg-purple-50 border-purple-200",
    description: "History, Geography, Civics",
  },
];

// Classes configuration
export const classesConfig = [
  {
    number: 8,
    color: "bg-blue-500",
    subjects: ["Mathematics", "Science", "English", "Social Science"],
    phase: "Phase 1 & 2",
    description: "Access Phase 1 & 2 question papers and concept videos for Class 8 subjects.",
  },
  {
    number: 9,
    color: "bg-green-500",
    subjects: ["Mathematics", "Science", "English", "Social Science"],
    phase: "Phase 1 & 2",
    description: "Access Phase 1 & 2 question papers and concept videos for Class 9 subjects.",
  },
  {
    number: 10,
    color: "bg-purple-500",
    subjects: ["Mathematics", "Science", "English", "Social Science"],
    phase: "Board Exam",
    description: "Complete NBSE Class 10 question papers and comprehensive video explanations.",
  },
  {
    number: 11,
    color: "bg-orange-500",
    subjects: ["Science", "Commerce", "Arts"],
    phase: "Stream-wise",
    description: "Stream-wise question papers and videos for Science, Commerce, and Arts.",
  },
  {
    number: 12,
    color: "bg-red-500",
    subjects: ["Science", "Commerce", "Arts"],
    phase: "Board Exam",
    description: "Complete NBSE Class 12 question papers and videos organized by stream.",
  },
];

// Available years for filtering
export const availableYears = Array.from({ length: 35 }, (_, i) => 2050 - i).filter(year => year >= 2016);

// Available phases
export const availablePhases = ["Phase 1", "Phase 2", "Board Exam"];

// Available subjects
export const availableSubjects = [
  "Mathematics",
  "Science",
  "English",
  "Social Science",
  "Physics",
  "Chemistry",
  "Biology",
  "History",
  "Geography",
  "Economics",
  "Political Science",
];
